In [2]:
from numpy.polynomial import Polynomial, Legendre

In [4]:
help(Legendre)

Help on class Legendre in module numpy.polynomial.legendre:

class Legendre(numpy.polynomial._polybase.ABCPolyBase)
 |  A Legendre series class.
 |  
 |  The Legendre class provides the standard Python numerical methods
 |  '+', '-', '*', '//', '%', 'divmod', '**', and '()' as well as the
 |  attributes and methods listed in the `ABCPolyBase` documentation.
 |  
 |  Parameters
 |  ----------
 |  coef : array_like
 |      Legendre coefficients in order of increasing degree, i.e.,
 |      ``(1, 2, 3)`` gives ``1*P_0(x) + 2*P_1(x) + 3*P_2(x)``.
 |  domain : (2,) array_like, optional
 |      Domain to use. The interval ``[domain[0], domain[1]]`` is mapped
 |      to the interval ``[window[0], window[1]]`` by shifting and scaling.
 |      The default value is [-1, 1].
 |  window : (2,) array_like, optional
 |      Window, see `domain` for its use. The default value is [-1, 1].
 |  
 |      .. versionadded:: 1.6.0
 |  
 |  Method resolution order:
 |      Legendre
 |      numpy.polynomial._p

In [9]:
from scipy.special import gegenbauer
help(gegenbauer)

Help on function gegenbauer in module scipy.special.orthogonal:

gegenbauer(n, alpha, monic=False)
    Return the nth order Gegenbauer (ultraspherical) polynomial,
    C^(alpha)_n(x), orthogonal over [-1,1] with weighting function
    (1-x**2)**(alpha-1/2) with alpha > -1/2



In [19]:
n = [i for i in range(4)]
l = [j for j in range(4)]
m = [k for k in range(4)]

In [32]:
# K_nl, I_nl
import numpy as np
from scipy.special import gamma
from math import pi
from math import factorial

Knl, Inl = np.zeros((len(n),len(l))), np.zeros((len(n), len(l)))


for i in range(len(n)):
    for j in range(len(l)):
        Knl[i,j] = 0.5*n[i]*(n[i] + 4*l[j] + 3) + (l[j] + 1)*(2*l[j] + 1)
        Inl[i,j] = Knl[i,j]*1/(2**(8*l[j] + 6))*gamma(n[i] + 4*l[j] + 3)/(factorial(n[i])*(n[i] + 2*l[j] + 3/2)*(gamma(2*l[j] + 3/2))**2 )
print(Knl)
print(Inl)

[[  1.   6.  15.  28.]
 [  3.  10.  21.  36.]
 [  6.  15.  28.  45.]
 [ 10.  21.  36.  55.]]
[[  2.65258238e-02   6.82092613e-03   8.61228047e-04   8.65644601e-05]
 [  1.43239449e-01   6.18935890e-02   1.12224639e-02   1.47305069e-03]
 [  4.09255568e-01   3.03841255e-01   7.78090833e-02   1.31799272e-02]
 [  8.84194128e-01   1.07980508e+00   3.82506838e-01   8.25895614e-02]]
